# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hh0Ybe82L3leRD2jOeIGGnsCloXo_2zf
"""

import requests
import json

# CONFIGURACION CONEXION IA - GEMINI
API_KEY = "CLAVE API" # Se debe generar una API KEY propia en el enlace https://aistudio.google.com/
MODELO = "models/gemini-2.5-flash"
URL = f"https://generativelanguage.googleapis.com/v1beta/{MODELO}:generateContent?key={API_KEY}"

# SEGMENTACION DE RESPUESTAS ESPECIALIZADAS - SISTEMAS DIGITALES
SYSTEM_PROMPT = """
Eres un experto en Sistemas Digitales y Semiconductores operando en el año 2026.

INSTRUCCIONES DE RESPUESTA:
1. ANÁLISIS 2026: Debes hablar en tiempo presente sobre los semiconductores en 2026 (ej. el auge de los chips de 1nm o 2nm, integración masiva de IA en hardware).
2. EMPRESAS CLAVE: Si te preguntan por empresas, menciona a NVIDIA, TSMC, ASML, Intel y Samsung, explicando cómo su tecnología permite los sistemas digitales actuales.
3. EDUCACIÓN: Si el usuario menciona 'Educación', debes estructurar tu respuesta bajo estas tres alternativas específicas:
- Si el usuario te saluda (ej. 'hola', 'buenas', 'qué tal'), responde saludando y explicando que eres un asistente especializado en Sistemas Digitales.
- Si el usuario pregunta '¿en qué me puedes ayudar?' o algo similar, responde indicando que puedes explicar y resolver dudas sobre: Compuertas lógicas, Circuitos, Arduino, Binario y Hexadecimal.
- Si el usuario pregunta sobre otros temas, responde amablemente que solo asesoras en Sistemas Digitales.
- Innovación en la Educación con semiconductores y sistemas digitales.
- Novedad e impacto de proyectos de sistemas digitales en la educación.
- Sistemas digitales y semiconductores en el futuro.

4. RESTRICCIÓN: Solo asesoras en temas de Sistemas Digitales y Semiconductores. Sé cordial y profesional.
"""

# FUNCION DE PREGUNTA IA - GEMINI
def preguntar_gemini(mensaje_usuario):
    payload = {
        "contents": [{
            "parts": [
                {"text": SYSTEM_PROMPT},
                {"text": f"Pregunta: {mensaje_usuario}"}
            ]
        }]
    }

    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(URL, headers=headers, data=json.dumps(payload))
        res_json = response.json()

        if response.status_code == 200:
            # Gemini devuelve candidatos, se toma el primero
            return res_json['candidates'][0]['content']['parts'][0]['text']
        else:
            return f"❌ Error {response.status_code}: {res_json.get('error', {}).get('message', 'Error desconocido')}"
    except Exception as e:
        return f"❌ Error de conexión: {str(e)}"

# INTERFAZ DEL CHATBOT
print("🤖 Chatbot Sistemas Digitales (Gemini API)")
print("Escribe 'salir' para terminar.\n")

while True:
    user_input = input("Tú: ")
    if user_input.lower() in ["salir", "exit", "chau", "chao", "adios", "terminar", "gracias", "eso es todo"]:
        print("Fue un placer ayudarte.\n 👋 Chat finalizado.")
        break
    respuesta = preguntar_gemini(user_input)


    print(f"\n🤖 Bot: {respuesta}\n")